function out = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OUT = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  OUT = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  out = importfile("/home/wilson/WorkDir/Mothership/src/out.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Oct-2021 19:37:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 34);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Elapsed_Time", "local_X", "local_Y", "local_Z", "R_target_X", "R_target_Y", "R_target_Z", "X_err_integrator", "Y_err_integrator", "visual_mode", "visual_first_enc", "Vis_counter", "Vis_last", "Vis_Consecutive", "Rendesvous_mode", "Algo_counter", "Algo_last", "Algo_consecutive", "Vis_app_dist","Vis_app_cnt", "Vis_app_last", "Vis_app_consecutive", "quad_radius", "safe_radius", "err_mag","quad_safe", "x_vis_err", "y_vis_err", "z_vis_err", "vis_int_x", "vis_int_y", "vis_int_z", "vis_der_x", "vis_der_y", "x_setpoint", "y_setpoint", "z_setpoint", "x_fade","y_fade","z_fade","fade_increment", "V_target_x", "V_target_y", "V_target_z"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double","double", "double","double","double","double","double","double","double","double","double","double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
out = readtable(filename, opts);

end